In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\Akash\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Akash\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Akash\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Akash\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Akash\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in C:\Users\Akash\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
print(f"Pandas version: {pd.__version__}")

Pandas version: 2.2.2

In [6]:
data={"Product":["A","B","C","D"],
      "Sales":[1000,800,1200,750],
      "Profit":[200,250,300,100]}

df=pd.DataFrame(data)
print("Sample DataFrame:\n",df)

Sample DataFrame:
   Product  Sales  Profit
0       A   1000     200
1       B    800     250
2       C   1200     300
3       D    750     100

In [7]:
display(df)

  Product  Sales  Profit
0       A   1000     200
1       B    800     250
2       C   1200     300
3       D    750     100

In [25]:
#Data frame:
#In series and Data frame:

In [9]:
#Series:
temps=pd.Series([72,68,75,80],name="Temperature")
print("Series Example:")
print(temps)

Series Example:
0    72
1    68
2    75
3    80
Name: Temperature, dtype: int64

In [10]:
import pandas as pd
data={"City":["New York","London","Chicago"],
      "Population": [8.4,3.9,2.7],
      "Area":[783.8,1302,606.1]}

cities=pd.DataFrame(data)
print("\nDataFrame Example:\n")
display(cities)

DataFrame Example:

       City  Population    Area
0  New York         8.4   783.8
1    London         3.9  1302.0
2   Chicago         2.7   606.1

In [11]:
#Attributes:
print("\nDataFrame Shape:",cities.shape)

DataFrame Shape: (3, 3)

In [13]:
print("Columns:",cities.columns)

Columns: Index(['City', 'Population', 'Area'], dtype='object')

In [14]:
print("Columns:",cities.columns.tolist())

Columns: ['City', 'Population', 'Area']

In [16]:
print("Index:",cities.index)

Index: RangeIndex(start=0, stop=3, step=1)

In [20]:
#Data I/O:
pd.date_range("20260701",periods=6,freq='YS')

DatetimeIndex(['2027-01-01', '2028-01-01', '2029-01-01', '2030-01-01',
               '2031-01-01', '2032-01-01'],
              dtype='datetime64[ns]', freq='YS-JAN')

In [21]:
pd.date_range("20260701",periods=6)

DatetimeIndex(['2026-07-01', '2026-07-02', '2026-07-03', '2026-07-04',
               '2026-07-05', '2026-07-06'],
              dtype='datetime64[ns]', freq='D')

In [23]:
pd.date_range("20260701",periods=6,freq='ME')

DatetimeIndex(['2026-07-31', '2026-08-31', '2026-09-30', '2026-10-31',
               '2026-11-30', '2026-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [24]:
pd.date_range("20260701",periods=6,freq='D')

DatetimeIndex(['2026-07-01', '2026-07-02', '2026-07-03', '2026-07-04',
               '2026-07-05', '2026-07-06'],
              dtype='datetime64[ns]', freq='D')

In [29]:
import numpy as np
dates=pd.date_range("20260701",periods=6)
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))
df

                   A         B         C         D
2026-07-01  0.046256  1.579911  0.515658  0.923091
2026-07-02  2.505471 -1.032469  1.198268  0.146029
2026-07-03  1.164389  0.033739  0.102669 -0.180861
2026-07-04  0.045683  0.522465 -0.102427  0.041964
2026-07-05 -1.313176 -1.334472 -1.657367  2.322832
2026-07-06 -0.668454  0.354840  0.363214  0.596920

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2026-07-01 to 2026-07-06
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes

In [34]:
pip install openpyxl

Collecting openpyxlNote: you may need to restart the kernel to use updated packages.

  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [35]:
dates=pd.date_range("20260701",periods=6)
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))
df.to_csv("sample_data.csv")
df.to_excel("sample_data.xlsx")
df.to_parquet("sample_data.parquet")

In [36]:
#Read from URL
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
titanic = pd.read_csv(url)
print("\nTitanic dataset:")
display(titanic.head())

Titanic dataset:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True